/**
 * Generate UI Imports Script
 *
 * Scans server/public/ and generates import statements that tell Bun
 * to embed these files into the compiled binary.
 *
 * Usage: bun run scripts/generate-ui-imports.ts
 * Called by: make build-ui (after copying UI dist to server/public/)
 *
 * Why this approach:
 * - Bun only embeds files imported with { type: 'file' } attribute
 * - No command-line glob support for embedding
 * - This script bridges the gap by generating import statements
 *
 * Output: src/modules/ui/imports.ts with import statements like:
 *   import '../../../public/index.html' with { type: 'file' }
 *   import '../../../public/assets/index-xyz.js' with { type: 'file' }
 *
 * @see imports.ts - Generated output (placeholder checked into git)
 * @see embedded-assets.ts - Runtime access to embedded files
 */

import { readdirSync, statSync, writeFileSync, existsSync } from "node:fs";
import { join, relative } from "node:path";

const PUBLIC_DIR = join(import.meta.dir, "../public");
const OUTPUT_FILE = join(import.meta.dir, "../src/modules/ui/imports.ts");

/** Recursively collect all files in a directory */
function getAllFiles(dir: string): string[] {
  const files: string[] = [];

  function walk(currentDir: string) {
    for (const entry of readdirSync(currentDir)) {
      const fullPath = join(currentDir, entry);
      if (statSync(fullPath).isDirectory()) {
        walk(fullPath);
      } else {
        files.push(fullPath);
      }
    }
  }

  walk(dir);
  return files;
}

function main() {
  if (!existsSync(PUBLIC_DIR)) {
    console.log("No public directory found. Skipping imports generation.");
    return;
  }

  console.log(`Scanning ${PUBLIC_DIR} for UI assets...`);
  const files = getAllFiles(PUBLIC_DIR);
  console.log(`Found ${files.length} files to embed`);

  const imports: string[] = [];

  for (const file of files) {
    const importPath = relative(
      join(import.meta.dir, "../src/modules/ui"),
      file,
    ).replace(/\\/g, "/");
    imports.push(`import '${importPath}' with { type: 'file' }`);

    const webPath = "/" + relative(PUBLIC_DIR, file).replace(/\\/g, "/");
    console.log(`  + ${webPath}`);
  }

  const content = `/* eslint-disable */
// AUTO-GENERATED by scripts/generate-ui-imports.ts - DO NOT EDIT
${imports.join("\n")}
`;

  writeFileSync(OUTPUT_FILE, content);
  console.log(`\nGenerated ${OUTPUT_FILE}`);
}

main();
